include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Core const rules
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    
    # Additional helpful rules
    unnecessary_const: true
    prefer_final_locals: true
    prefer_final_fields: true

analyzer:
  errors:
    # Treat missing const as a warning (not error)
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning